exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('recipes_ingredients').del()
    .then(function () {
      // Inserts seed entries
      return knex('recipes_ingredients').insert([
        { quantity: '1/4',
        recipes_id: 1,
        ingredients_id: 1,
        measurement: 'oz'},
        { quantity: '1',
          recipes_id: 1,
          ingredients_id: 2,
          measurement: 'teaspoon'},
        { quantity: '1-1/4',
          recipes_id: 1,
          ingredients_id: 3,
          measurement: 'cup'},
        { quantity: '1/4',
          recipes_id: 1,
          ingredients_id: 4,
          measurement: 'cup'},
        { quantity: '1',
          recipes_id: 1,
          ingredients_id: 5,
          measurement: 'teaspoon'},
        { quantity: '3-1/2',
          recipes_id: 1,
          ingredients_id: 6,
          measurement: 'cup'},
        { quantity: '1/2',
          recipes_id: 1,
          ingredients_id: 7,
          measurement: 'lb'},
        { quantity: '1',
          recipes_id: 1,
          ingredients_id: 8,
          measurement: 'small'},
        { quantity: '15',
          recipes_id: 1,
          ingredients_id: 9,
          measurement: 'oz'},
        { quantity: '3',
          recipes_id: 1,
          ingredients_id: 10,
          measurement: 'teaspoon'},
        { quantity: '1',
          recipes_id: 1,
          ingredients_id: 11,
          measurement: 'teaspoon'},
        { quantity: '1',
          recipes_id: 1,
          ingredients_id: 12,
          measurement: 'medium'},
        { quantity: '2',
          recipes_id: 1,
          ingredients_id: 13,
          measurement: 'cup'}
      ]);
    });
};